version: "0.1"

queue: default
jobSetId: testing
jobs:
  - priority: 1
    namespace: personal-anonymous
    ingress:
      - tlsEnabled: false
        ports:
          - 8888
        useClusterIP: true
    services:
      - type: NodePort
        ports:
          - 8888
    podSpec:
      restartPolicy: Never
      containers:
        - name: jupyterlab
          imagePullPolicy: IfNotPresent
          image: jupyter/tensorflow-notebook:latest
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 1
          ports:
            - containerPort: 8888
              name: jupyterlab
          env:
            - name: JUPYTER_TOKEN
              value: testing
  - priority: 1
    namespace: personal-anonymous
    ingress:
      - tlsEnabled: false
        ports:
          - 8888
        useClusterIP: true
    services:
      - type: NodePort
        ports:
          - 8888
    podSpec:
      restartPolicy: Never
      containers:
        - name: jupyterlab
          imagePullPolicy: IfNotPresent
          image: jupyter/tensorflow-notebook:latest
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 1
          ports:
            - containerPort: 8888
              name: jupyterlab
          env:
            - name: JUPYTER_TOKEN
              value: testing