name: Release Armada Jupyter to PYPI

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/lint-and-unit
        with:
          python-version: '3.8'
          path: 'client/python'

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: client/python/dist/